#!/usr/bin/env bash

pushd $(dirname $0) > /dev/null
source ./lib/bash/separator
pluginsdir="./plugins/"
jsonstring=""

echo '{ "version": 1 }'
echo '['
echo '[]'

while [ true ]; do
	for i in `cat $pluginsdir"/.order"`; do
		jsonstring=$jsonstring$separator`$pluginsdir$i`
	done
	echo -e ",[${jsonstring%,}]"
	jsonstring=""
	sleep 5
done
