#!/usr/bin/env bash

source $HOME/.infobar/lib/bash/separator
pluginsdir=$HOME"/.infobar/plugins/"
jsonstring=""

echo '{ "version": 1 }'
echo '['
echo '[]'

while [ true ]; do
	for i in `cat $pluginsdir"/.order"`; do
		jsonstring=$jsonstring$separator`$pluginsdir$i`
	done
	echo -e ",[${jsonstring%,}]"
	jsonstring=""
	sleep 5
done
