#!/usr/bin/env bash

set -x
source $HOME"/.infobar/lib/bash/jsonify"
curler="curl -m 5"
pluginname="rur-uah"

currency=`$curler -s http://www.cbr.ru/scripts/XML_daily.asp | sed -n 's:[Value/<>\t\r]::g;204p'`
currency=`echo $currency"/10"|bc`
plugintext="UAH: $currency RUR"
plugincolor="#00FFFF"

jsonify "$pluginname" "$plugintext" "$plugincolor"
